// <auto-generated />
using Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20220905164041_Initial-Commit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Demo.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Email = "liyojose@gmail.com",
                            Firstname = "Liyo",
                            Lastname = "Jose"
                        },
                        new
                        {
                            Id = 1002,
                            Email = "roger@gmail.com",
                            Firstname = "Roger",
                            Lastname = "Wan"
                        },
                        new
                        {
                            Id = 1003,
                            Email = "pedro@gmail.com",
                            Firstname = "Pedro",
                            Lastname = "hugo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
